SSMI_HEADER = u"SSMI"

SSMI_SEND_LOGIN = u"1"
SSMI_SEND_SMS = u"2"
SSMI_SEND_LINK_CHECK = u"3"
SSMI_SEND_BINARY = u"4"
SSMI_SEND_LOGOUT = u"99"
SSMI_SEND_USSD = u"110"
SSMI_SEND_WAP_PUSH = u"112"

SSMI_RESPONSE_SEQ = u"100"
SSMI_RESPONSE_ACK = u"101"
SSMI_RESPONSE_NACK = u"102"
SSMI_RESPONSE_TEXT_MESSAGE = u"103"
SSMI_RESPONSE_DELIVERY_MESSAGE = u"104"
SSMI_RESPONSE_FREEFORM_MESSAGE = u"105"
SSMI_RESPONSE_BINARY_MESSAGE = u"106"
SSMI_RESPONSE_PREMIUMRATED_MESSAGE = u"107"
SSMI_RESPONSE_BINARY_PREMIUMRATED_MESSAGE = u"108"
SSMI_RESPONSE_USSD = u"110"
SSMI_RESPONSE_USSD_EXTENDED = u"111"
SSMI_RESPONSE_EXTENDED_RETURN = u"113"
SSMI_RESPONSE_EXTENDED_RETURN_BINARY = u"116"
SSMI_RESPONSE_EXTENDED_PREMIUMRATED_MESSAGE = u"117"
SSMI_RESPONSE_EXTENDED_BINARY_PREMIUMRATED_MESSAGE = u"118"
SSMI_RESPONSE_REMOTE_LOGOUT = u"199"

SSMI_USSD_TYPE_NEW = u"1"
SSMI_USSD_TYPE_EXISTING = u"2"
SSMI_USSD_TYPE_END = u"3"
SSMI_USSD_TYPE_TIMEOUT = u"4"
SSMI_USSD_TYPE_REDIRECT = u"5"
SSMI_USSD_TYPE_NI = u"6"

ack_reason = {
    "1": "Login OK",
    "2": "Link check response",
}

nack_reason = {
    "1": "Invalid username/password combination",
    "2": "Invalid/unknown message type",
    "3": "Could not parse message",
    "4": "Account suspended (non-payment or abuse)",
}

# SSMI_RESPONSE_SEQ = u"100"
# SSMI_RESPONSE_TEXT_MESSAGE = u"103"
# SSMI_RESPONSE_DELIVERY_MESSAGE = u"104"
# SSMI_RESPONSE_FREEFORM_MESSAGE = u"105"
# SSMI_RESPONSE_BINARY_MESSAGE = u"106"
# SSMI_RESPONSE_PREMIUMRATED_MESSAGE = u"107"
# SSMI_RESPONSE_BINARY_PREMIUMRATED_MESSAGE = u"108"
# SSMI_RESPONSE_USSD_EXTENDED = u"111"
# SSMI_RESPONSE_EXTENDED_RETURN = u"113"
# SSMI_RESPONSE_EXTENDED_RETURN_BINARY = u"116"
# SSMI_RESPONSE_EXTENDED_PREMIUMRATED_MESSAGE = u"117"
# SSMI_RESPONSE_EXTENDED_BINARY_PREMIUMRATED_MESSAGE = u"118"
